import type { Metadata } from "next";
import { Momo_Trust_Display, Open_Sans } from "next/font/google";
import "./globals.css";

const momoTrust = Momo_Trust_Display({
  variable: "--font-momo-trust",
  subsets: ["latin"],
  weight: ["400"]
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${momoTrust.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
